travis:
  secure:
    BINSTAR_TOKEN: yX9kRpD/2/NippVrqwV4QgDlolxEU/DHVMVU1WgB1UY5D8I5qO5VQe+nPPCVq9HL2pzA5d5CDsk4nVxB+JdI8UyjJ9GOazEKippGa81juEqfMZwkInAyRxNrRVB1zlw+z6nDaGIa5fJOw+VmFq1gxEGouWT4GdXOeeM1k8Z+xXKcEGvxrn4j/e7jdpBsHKIbBUzX55x6OHL/CkRK/KQMB0PXP4tV2+rq1jSFziHZjE/vHVghhrNXRvFmyVBZoUhSAVM5hlT8Ix/FgmgBV234lhqSu5RyrDm+G6N5k3Ot4w1jt8nzKloodPGjuNgwG+ZX++GDvHczN2pPdMgfcAIl8F+v1dxwqPU82T10gHARKnIUdTw78/PDNUJcx/ZLrbI5p2EPeW5LiVYPCOpvFgMxRgydiPx7acciik/d2gOKETZY2KC6eoEdmSE/4RkOpZsAiVZ9vZZmJDGxDHcH3PHlI/hyHTVCcdte7YhiIo52kyw2l0W/MkjA9HTDICbjgmQT3uFpd04GX2SOrVPLANHPmSXluy01W+2rfaGiGqvF/DuMOOWrlJX0LZNwto7MRgv0TEi87/wTOT2RCS1bWnpSG9kSGhHu+xBTxjH6AIjvIb1jxg3ihBT6U5ikOoArkZ1ASMWxvbHSkrKp1VkNqTbcbYSEODelXrggTYAGmjT9rwE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
